routes/web.php
<?php
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Socialite 
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('user.local_currency/{id}', 'UserController@setLocalCurrency')->name('user.local_currency');
Route::post('user/store_exchange_rates/{id}', 'UserController@store_exchange_rates')->name('user.store_exchange_rates');
Route::get('user/exchange_rates/{id}', 'UserController@exchange_rates')->name('user.exchange_rates');


Route::resource('currency', 'CurrencyController');
Route::post('currency/add', 'CurrencyController@add')->name('currency.add');

Route::resource('account', 'AccountController');
Route::post('account/{id}/transactions', 'AccountController@transactions')->name('account.transactions');

Route::resource('transaction', 'TransactionController');
Route::resource('category', 'CategoryController');

app/Currency.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Currency extends Model
{
    protected $fillable = [
        'default_currency_id', 
        'user_id', 
        'name', 
        'symbol', 
        'description', 
        'country',
        'exchange_rate'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function accounts()
    {
        return $this->hasMany(Account::class);
    }

}

app/Http/Controllers/CurrencyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Currency;
use Auth;

class CurrencyController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('currencyNotRelated', 
            ['only' => 
                ['edit', 'update', 'show', 'destroy']
        ]);
        $this->middleware('currencyByUser', 
            ['only' => 
                ['edit', 'update']
        ]);
    }

    public function index()
    {
        return view('currency.index', [
            'currencies' => Auth::user()
                ->currencies()
                ->orderBy('country', 'ASC')
                ->paginate(10)
        ]);
    }

    public function create()
    {
        return view('currency.create', [
            'currencies' => Currency::where('user_id', null)
                            ->whereNotIn('id', 
                                Auth::user()->currenciesIds()
                            )->orderBy('country')
                            ->get()
        ]); 
    }

    public function add(Request $request)
    {
        $request->validate([
            'currency' => 'required|
                exists:currencies,id,user_id,"NULL"|
                unique:currencies,default_currency_id,null,null,user_id,' . Auth::user()->id
        ]);
        $default_currency = Currency::find($request['currency']);
        Currency::create([
            'default_currency_id' => $default_currency->id,
            'user_id' => Auth::user()->id,
            'name' => $default_currency->name,
            'symbol' => $default_currency->symbol,
            'description' => $default_currency->description,
            'country' => $default_currency->country
        ]);
        return redirect(route('currency.index'))->with([
            'message-success' => 'Currency added to your list'
        ]);
    }

    public function store(Request $request)
    {
        $currency = Currency::create($request->validate([
            'name' => 'required|unique:currencies,name,null,null,user_id,' . Auth::user()->id,
            'symbol' => 'required',
            'description' => 'required|unique:currencies,description,null,null,user_id,' . Auth::user()->id,
            'country' => 'required'
        ]));
        $currency->update([
            'user_id' => Auth::user()->id
        ]);
        return redirect(route('currency.index'))->with([
            'message-success' =>'Currency created and added to your list!'
        ]);
    }

    public function show(Currency $currency)
    {
        return view('currency.delete', [
            'currency' => $currency
        ]);
    }

    public function edit(Currency $currency)
    {
        return view('currency.update', [
            'currency' => $currency
        ]);
    }

    public function update(Request $request, Currency $currency)
    {
        $currency->update($request->validate([
            'name' => 'required|unique:currencies,name,' . $currency->name . ',name,user_id,' . Auth::user()->id,
            'symbol' => 'required',
            'description' => 'required|unique:currencies,description,' . $currency->description . ',description,user_id,' . Auth::user()->id,
            'country' => 'required'
        ]));
        return redirect(route('currency.index'))->with([
            'message-success' => 'Currency correctly updated'
        ]);
    }

    public function destroy(Currency $currency)
    {
        if ($currency->accounts()->exists()) {
            return redirect()->back()->withErrors([
                'error' => 'This currency has accounts related to it, you can\'t delete it'
            ]);
        }
        if (Auth::user()->local_currency == $currency->id) {
            Auth::user()->resetExchangeRates();
            Auth::user()->update([
                'local_currency' => null
            ]);
        }
        $currency->delete();
        return redirect(route('currency.index'))->with([
            'message-success' => 'Currency deleted correctly!'
        ]);
    }
}

resources/views/currency/create.blade.php
@extends('layouts.app')

@section('styles')
  <style>
    .card-text {
      padding-bottom: 1.25rem;
      margin: 0;
    }
  </style>
@endsection

@section('content')
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="card">
          <div class="card-header">
            <h5 class="card-title">Add Currency</h5>
          </div>
          <div class="card-body">
            @if (session('message-info'))
              <p class="message message-info">{{ session('message-info') }}</p>
            @endif
            @if (count($currencies) > 0)
              <p class="card-text">Here you can add one of our default currencies</p>
              <form method="post" action="{{ route('currency.add') }}">
                @csrf
                <div class="form-group">
                  <select class="form-control @error('currency') is-invalid @enderror" name="currency" id="currency">
                    @foreach ($currencies as $currency)
                      <option value="{{ $currency->id }}">
                        {{ $currency->country }} - {{ $currency->name }} - {{ $currency->description }}
                      </option>
                    @endforeach
                  </select>
                </div>
                @error('currency')
                  <p class="message message-danger">{{ $errors->first('currency') }}</p>
                @enderror
      
                <button type="submit" class="btn btn-outline-success">Add</button>
                <a class="btn btn-outline-primary" href="{{ route('currency.index') }}">Back</a>
              </form>
            @else
              <p class="card-text">You have added all of our default currencies, try creating your own</p>
            @endif
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card">
          <div class="card-header">
            <h5 class="card-title">Create Currency</h5>
          </div>
          <div class="card-body">
            <p class="card-text">If you want to create a new currency, you can do it here.</p>
            <form method="post" action="{{ route('currency.store') }}">
              @csrf
    
              <div class="form-group">
                <label for="name">Name:</label>
                <input 
                  id="name" 
                  class="form-control @error('name') is-invalid @enderror" 
                  type="text" 
                  name="name"
                  value="{{ old('name') }}">
              </div>
              @error('name')
                <p class="message message-danger">{{ $errors->first('name') }}</p>
              @enderror
    
              <div class="form-group">
                <label for="symbol">Symbol:</label>
                <input 
                  id="symbol" 
                  class="form-control @error('symbol') is-invalid @enderror" 
                  type="text" 
                  name="symbol"
                  value="{{ old('symbol') }}">
              </div>
              @error('symbol')
                <p class="message message-danger">{{ $errors->first('symbol') }}</p>
              @enderror
    
              <div class="form-group">
                <label for="description">Description:</label>
                <input 
                  id="description" 
                  class="form-control @error('description') is-invalid @enderror" 
                  type="text" 
                  name="description"
                  value="{{ old('description') }}">
              </div>
              @error('description')
                <p class="message message-danger">{{ $errors->first('description') }}</p>
              @enderror
    
              <div class="form-group">
                <label for="country">Country:</label>
                <input 
                  id="country" 
                  class="form-control @error('country') is-invalid @enderror" 
                  type="text" 
                  name="country"
                  value="{{ old('country') }}">
              </div>
              @error('country')
                <p class="message message-danger">{{ $errors->first('country') }}</p>
              @enderror
    
              <button type="submit" class="btn btn-outline-success">Create</button>
              <a class="btn btn-outline-primary" href="{{ route('currency.index') }}">Back</a>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
@endsection

resources/views/currency/delete.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="card">
      <div class="card-header">
        Delete Currency
        @error('error')
          <p class="message message-danger">{{ $errors->first('error') }}</p>
        @enderror
      </div>
      <div class="card-body">
        <form method="post" action="{{ route('currency.destroy', $currency->id) }}">
          @csrf
          @method('DELETE')

          <div class="form-group">
            <label for="name">Name:</label>
            <input 
              id="name" 
              class="form-control"
              type="text" 
              name="name"
              value="{{ $currency->name }}"
              readonly>
          </div>
          
          <div class="form-group">
            <label for="symbol">Symbol:</label>
            <input 
              id="symbol" 
              class="form-control"
              type="text" 
              name="symbol"
              value="{{ $currency->symbol }}"
              readonly>
          </div>
          
          <div class="form-group">
            <label for="description">Description:</label>
            <input 
              id="description" 
              class="form-control"
              type="text" 
              name="description"
              value="{{ $currency->description }}"
              readonly>
          </div>
          
          <div class="form-group">
            <label for="country">Country:</label>
            <input 
              id="country" 
              class="form-control"
              type="text" 
              name="country"
              value="{{ $currency->country }}"
              readonly>
          </div>
          
          <button type="submit" class="btn btn-outline-danger">Delete</button>
          <a class="btn btn-outline-primary" href="{{ route('currency.index') }}">Back</a>
        </form>
      </div>
    </div>
  </div>
@endsection

resources/views/currency/exchange_rates.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Set Exchange Rates</h5>
      </div>
      <div class="card-body">
        <form class="form" method="post" action="{{ route('user.store_exchange_rates', $currency->id) }}">
          @csrf
          <div class="form-group">
            <label 
              for="exchange_rate">
              {{ $currency->name }} - {{ $currency->description }} - {{ $currency->country }}
            </label>
            <input 
              id="exchange_rate" 
              class="form-control @error('name') is-invalid @enderror" 
              type="number" 
              step=".000001" 
              name="exchange_rate">
            @error('exchange_rate')
              <p class="message message-danger">{{ $errors->first('exchange_rate') }}</p>
            @enderror
          </div>
          <button type="submit" class="btn btn-outline-success">Save</button>
          <a class="btn btn-outline-primary" href="{{ route('currency.index') }}">Back</a>
        </form>
      </div>
    </div>
  </div>
@endsection

resources/views/currency/index.blade.php
@extends('layouts.app')

@section('styles')
  <style>
    a {
      text-decoration: none;
    }
    .fa-hand-holding-heart {
      color: red;
    }
    tr {
      text-align: center;
    }
    .btn {
      margin: 1.5rem 0 1.5rem 0;
    }
  </style>
@endsection

@section('content')
  <div class="container">
    <a class="btn btn-outline-light" href="{{ route('currency.create') }}">Add / Create</a>
    @if (session('message-success'))
      <p class="message message-success">{{ session('message-success') }}</p>
    @endif
    @if (session('message-info'))
      <p class="message message-info">{{ session('message-info') }}</p>
    @endif
    @error('error')
      <p class="message message-danger">{{ $message }}</p>
    @enderror
    <table class="table table-sm table-hover">
      <thead>
        <tr>
          <th>Short Name</th>
          <th>Symbol</th>
          <th>Description</th>
          <th>Country</th>
          <th>Local Currency</th>
          <th>Exchange Rate</th>
          <th>Options</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($currencies as $currency)
          <tr>
            <td>{{ $currency->name }}</td>
            <td>{{ $currency->symbol }}</td>
            <td>{{ $currency->description }}</td>
            <td>{{ $currency->country }}</td>
            <td>
              @if (Auth::user()->local_currency == $currency->id)
                <i class="fas fa-hand-holding-heart fa-lg"></i>
              @else
                <a href="{{ route('user.local_currency', $currency->id) }}">
                  <i class="fas fa-hand-holding fa-lg"></i>
                </a>
              @endif
            </td>
            <td>
              @if ($currency->exchange_rate)
                {{ $currency->exchange_rate }}
              @else
                <a href="{{ route('user.exchange_rates', $currency->id) }}">
                  <i class="fas fa-hand-holding fa-lg"></i>
                </a>
              @endif
            </td>
            <td>
              <a href="{{ route('currency.edit', $currency->id) }}">
                <i class="fas fa-edit fa-lg"></i>
              </a>
              -
              <a href="{{ route('currency.show', $currency->id) }}">
                <i class="fas fa-trash-alt fa-lg"></i>
              </a>
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>
    {{ $currencies->links() }}
  </div>
@endsection

resources/views/currency/update.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="card">
      <div class="card-header">
        Update Currency
      </div>
      <div class="card-body">
        <form method="post" action="{{ route('currency.update', $currency->id) }}">
          @csrf
          @method('PUT')

          <div class="form-group">
            <label for="name">Name:</label>
            <input 
              id="name" 
              class="form-control @error('name') is-invalid @enderror" 
              type="text" 
              name="name"
              value="{{ $currency->name }}">
          </div>
          @error('name')
            <p class="message message-danger">{{ $errors->first('name') }}</p>
          @enderror

          <div class="form-group">
            <label for="symbol">Symbol:</label>
            <input 
              id="symbol" 
              class="form-control @error('symbol') is-invalid @enderror" 
              type="text" 
              name="symbol"
              value="{{ $currency->symbol }}">
          </div>
          @error('symbol')
            <p class="message message-danger">{{ $errors->first('symbol') }}</p>
          @enderror

          <div class="form-group">
            <label for="description">Description:</label>
            <input 
              id="description" 
              class="form-control @error('description') is-invalid @enderror" 
              type="text" 
              name="description"
              value="{{ $currency->description }}">
          </div>
          @error('description')
            <p class="message message-danger">{{ $errors->first('description') }}</p>
          @enderror

          <div class="form-group">
            <label for="country">Country:</label>
            <input 
              id="country" 
              class="form-control @error('country') is-invalid @enderror" 
              type="text" 
              name="country"
              value="{{ $currency->country }}">
          </div>
          @error('country')
            <p class="message message-danger">{{ $errors->first('country') }}</p>
          @enderror

          <button type="submit" class="btn btn-outline-success">Update</button>
          <a class="btn btn-outline-primary" href="{{ route('currency.index') }}">Back</a>
        </form>
      </div>
    </div>
  </div>
@endsection