routes/web.php
<?php
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Socialite 
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('user.local_currency/{id}', 'UserController@setLocalCurrency')->name('user.local_currency');
Route::post('user/store_exchange_rates/{id}', 'UserController@store_exchange_rates')->name('user.store_exchange_rates');
Route::get('user/exchange_rates/{id}', 'UserController@exchange_rates')->name('user.exchange_rates');


Route::resource('currency', 'CurrencyController');
Route::post('currency/add', 'CurrencyController@add')->name('currency.add');

Route::resource('account', 'AccountController');
Route::post('account/{id}/transactions', 'AccountController@transactions')->name('account.transactions');

Route::resource('transaction', 'TransactionController');
Route::resource('category', 'CategoryController');

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\Transaction;
use App\Account;
use App\Kind;

class TransactionController extends Controller
{
    public function index()
    {
        return view('transaction.index', [
            'transactions' => Auth::user()->transactions()->paginate(10)
        ]);
    }

    public function create()
    {
        if (!Auth::user()->localCurrency) {
            return redirect(route('currency.index'))->withErrors([
                'error' => 'Please define your local currency first!'
            ]);
        }
        return view('transaction.create', [
            'accounts' => Auth::user()->accounts,
            'kinds' => Kind::all(),
            'categories' => Auth::user()->categories
        ]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'account_from' => 'required|exists:accounts,id,user_id,' . Auth::user()->id,
            'kind_id' => 'required|exists:kinds,id',
            'category_id' => 'required|exists:categories,id,user_id,' . Auth::user()->id,
            'amount' => 'required|numeric|min:.000001',
            'detail' => 'required',
            'date' => 'required|max:' . date('Y-m-d')
        ]);
        $account_from = Account::find($request['account_from']);
        /*
        $request->validate([
            'amount' => 'numeric|max:' . $account_from->balance
        ]);
        */
        if (!$account_from->currency->exchange_rate) {
            return redirect()->back()->withErrors([
                'account_from' => 'Please define the exchange rate for this account first!'
            ]);
        }
        $kind_selected = Kind::find($request['kind_id']);
        $kind_income = Kind::where('name', 'Income')->first();
        $kind_expense = Kind::where('name', 'Expense')->first();
        if ($kind_selected->name == 'Transfer') {
            $request->validate([
                'account_to' => 'required|exists:accounts,id,user_id,' . Auth::user()->id
            ]);
            $account_to = Account::find($request['account_to']);
            if (!$account_to->currency->exchange_rate) {
                return redirect()->back()->withErrors([
                    'account_to' => 'Please define the exchange rate for this account first!'
                ]);
            }
            $ammount_exchanged;
            switch (Auth::user()->local_currency) {
                case $account_from->currency->id:
                    $ammount_exchanged = $request['amount'] * $account_to->currency->exchange_rate;
                    break;
                case  $account_to->currency->id:
                    $ammount_exchanged = $request['amount'] / $account_to->currency->exchange_rate;
                    break;
                default:
                    $ammount_exchanged = ($request['amount'] / $account_from->currency->exchange_rate) * $account_to->currency->exchange_rate;
            }
            $account_from->update([
                'balance' => $account_from->balance - $request['amount']
            ]);
            $account_to->update([
                'balance' => $account_to->balance + $request['amount']
            ]);
            $transaction_from = Transaction::create([
                'account_id' => $account_from->id,
                'kind_id' => $kind_expense->id,
                'category_id' => $request['category_id'],
                'amount' => $request['amount'],
                'detail' => $request['detail'],
                'date' => $request['date']
            ]);
            $transaction_to = Transaction::create([
                'account_id' => $account_to->id,
                'kind_id' => $kind_income->id,
                'category_id' => $request['category_id'],
                'pair' => $transaction_from->id,
                'amount' => $ammount_exchanged,
                'detail' => $request['detail'],
                'date' => $request['date']
            ]);
            $transaction_from->update([
                'pair' => $transaction_to->id
            ]);
        } else {
            $transaction_from = Transaction::create([
                'account_id' => $account_from->id,
                'kind_id' => $request['kind_id'],
                'category_id' => $request['category_id'],
                'amount' => $request['amount'],
                'detail' => $request['detail'],
                'date' => $request['date']
            ]);
            switch ($kind_selected->name) {
                case 'Expense':
                    $account_from->update([
                        'balance' => $account_from->balance - $request['amount']
                    ]);
                    $transaction_from->update([
                        'kind_id' => $kind_expense->id
                    ]);
                    break;
                case 'Income':
                    $account_from->update([
                        'balance' => $account_from->balance + $request['amount']
                    ]);
                    $transaction_from->update([
                        'kind_id' => $kind_income->id
                    ]);
                    break;
            }
        }
        return redirect(route('transaction.index'))->with([
            'message-success' => 'Transaction created correctly!'
        ]);
    }


    public function show(Transaction $transaction)
    {
        if ($transaction->pair) {
            $transaction_from = $transaction;
            $transaction_pair = Transaction::find($transaction->pair);
            $transaction_to = $transaction_pair;
            if ($transaction->id > $transaction_pair->id) {
                $transaction_from = $transaction_pair;
                $transaction_to = $transaction;
            }
            return view('transaction.delete', [
                'transaction' => $transaction,
                'transaction_from' => $transaction_from,
                'transaction_to' => $transaction_to
            ]);
        }
        return view('transaction.delete', [
            'transaction' => $transaction
        ]);
        
    }

    public function edit(Transaction $transaction)
    {
        return view('transaction.update', [
            'transaction' => $transaction
        ]);
    }

    public function update(Request $request, Transaction $transaction)
    {
        $request->validate([
            'amount' => 'required|numeric|min:.000001|max:' . ($transaction->account->balance + $transaction->amount),
            'detail' => 'required',
            'date' => 'required|max:' . date('Y-m-d')
        ]);
        switch ($transaction->category->description) {
            case 'Transfer':
                $transaction_from = $transaction;
                $transaction_pair = Transaction::find($transaction->pair);
                $transaction_to = $transaction_pair;
                if ($transaction->id > $transaction_pair->id) {
                    $transaction_from = $transaction_pair;
                    $transaction_to = $transaction;
                }
                $ammount_exchanged =  $request['amount'] - $transaction->amount;
                switch (Auth::user()->local_currency) {
                    case $transaction_from->account->currency->id:
                        $ammount_exchanged = $request['amount'] * $transaction_to->account->currency->exchange_rate;
                        break;
                    case  $transaction_to->account->currency->id:
                        $ammount_exchanged = $request['amount'] / $transaction_to->account->currency->exchange_rate;
                        break;
                    default:
                        $ammount_exchanged = ($request['amount'] / $transaction_from->account->currency->exchange_rate) * $transaction_to->account->currency->exchange_rate;
                }
                $transaction_from->account->update([
                    'balance' => $transaction_from->account->balance + $transaction->amount - $request['amount']
                ]);
                $transaction_to->account->update([
                    'balance' => $transaction_to->account->balance - $transaction->amount + $request['amount']
                ]);
                if($transaction->id == $transaction_from->id) {
                    $transaction_from->update([
                        'amount' => $request['amount'],
                        'detail' => $request['detail'],
                        'date' => $request['date']
                    ]);
                    $transaction_to->update([
                        'amount' => $ammount_exchanged,
                        'detail' => $request['detail'],
                        'date' => $request['date']
                    ]);
                } else {
                    $transaction_from->update([
                        'amount' => $ammount_exchanged,
                        'detail' => $request['detail'],
                        'date' => $request['date']
                    ]);
                    $transaction_to->update([
                        'amount' => $request['amount'],
                        'detail' => $request['detail'],
                        'date' => $request['date']
                    ]);
                }
                break;
            
            case 'Expense':
                $transaction->account->update([
                    'balance' => $transaction->account->balance + $transaction->amount - $request['amount']
                ]);
                $transaction->update([
                    'amount' => $request['amount'],
                    'detail' => $request['detail'],
                    'date' => $request['date']
                ]);
                break;
            case 'Income':
                $transaction->account->update([
                    'balance' => $transaction->account->balance - $transaction->amount + $request['amount']
                ]);

resources/views/transaction/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Create an Transaction</h5>
      </div>
      <div class="card-body">
        <form method="post" action="{{ route('transaction.store') }}">
          @csrf

          <div class="row">

            <div class="col-md-4">
              <div class="form-group">
                <label for="account_from">Account From:</label>
                <select class="form-control @error('account_from') is-invalid @enderror" name="account_from" id="account">
                  @foreach ($accounts as $account)
                    @if (old('account_from') == $account->id)
                      <option value="{{ $account->id }}" selected>
                        {{ $account->name }} - {{ $account->currency->name }}
                      </option>
                    @else
                      <option value="{{ $account->id }}">
                        {{ $account->name }} - {{ $account->currency->name }}
                      </option>
                    @endif
                  @endforeach
                </select>
              </div>
              @error('account_from')
                <p class="message message-danger">{{ $errors->first('account_from') }}</p>
              @enderror
              <div class="form-group" id="account_to" hidden>
                <label for="account_to">Account To:</label>
                <select class="form-control @error('account_to') is-invalid @enderror" name="account_to" id="account">
                  @foreach ($accounts as $account)
                    @if (old('account_to') == $account->id)
                      <option value="{{ $account->id }}" selected>
                        {{ $account->name }} - {{ $account->currency->name }}
                      </option>
                    @else
                      <option value="{{ $account->id }}">
                        {{ $account->name }} - {{ $account->currency->name }}
                      </option>
                    @endif
                  @endforeach
                </select>
              </div>
              @error('account_to')
                <p class="message message-danger">{{ $errors->first('account_to') }}</p>
              @enderror
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <label for="kind_id">Kind:</label>
                <select class="form-control @error('kind_id') is-invalid @enderror" name="kind_id" id="kind" onchange="kindChanged()">
                  @foreach ($kinds as $kind)
                    @if (old('kind_id') == $kind->id)
                      <option value="{{ $kind->id }}" selected>
                        {{ $kind->name }}
                      </option>
                    @else
                      <option value="{{ $kind->id }}">
                        {{ $kind->name }}
                      </option>
                    @endif
                  @endforeach
                </select>
              </div>
              @error('kind_id')
                <p class="message message-danger">{{ $errors->first('kind_id') }}</p>
              @enderror
              <div class="form-group">
                <label for="category_id">Category:</label>
                <select class="form-control @error('category_id') is-invalid @enderror" name="category_id" id="category">
                  @foreach ($categories as $category)
                    @if (old('category_id') == $category->id)
                      <option value="{{ $category->id }}" selected>
                        {{ $category->description }}
                      </option>
                    @else
                      <option value="{{ $category->id }}">
                        {{ $category->description }}
                      </option>
                    @endif
                  @endforeach
                </select>
              </div>
              @error('category_id')
                <p class="message message-danger">{{ $errors->first('category_id') }}</p>
              @enderror
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <label for="date">Date:</label>
                <input 
                  id="date" 
                  class="form-control" 
                  type="date" 
                  name="date" 
                  max="{{ date('Y-m-d') }}" 
                  value="{{ old('date') }}"
                >
              </div>
              @error('date')
                <p class="message message-danger">{{ $errors->first('date') }}</p>
              @enderror
            </div>

          </div>

          <div class="row">

            <div class="col-md-6">
              <div class="form-group">
                <label for="amount">Amount:</label>
                <input 
                  id="amount" 
                  class="form-control @error('amount') is-invalid @enderror" 
                  type="number" 
                  name="amount"
                  step=".000001"
                  min=".000001"
                  value="{{ old('amount') }}">
              </div>
              @error('amount')
                <p class="message message-danger">{{ $errors->first('amount') }}</p>
              @enderror
            </div>

            <div class="col-md-6">
              <div class="form-group">
                <label for="detail">Detail:</label>
                <input 
                  id="detail" 
                  class="form-control @error('detail') is-invalid @enderror" 
                  type="text" 
                  name="detail"
                  value="{{ old('detail') }}">
              </div>
              @error('detail')
                <p class="message message-danger">{{ $errors->first('detail') }}</p>
              @enderror
            </div>

          </div>

          <button type="submit" class="btn btn-outline-success">Create</button>
          <a class="btn btn-outline-primary" href="{{ route('transaction.index') }}">Back</a>
        </form>
      </div>
    </div>
  </div>
  
@endsection

@section('javascript')
  <script type="text/javascript">
    function kindChanged() {
      var kind = document.getElementById('kind');
      if (kind.options[kind.selectedIndex].text == 'Transfer') {
        document.getElementById('account_to').hidden = false;
      } else {
        document.getElementById('account_to').hidden = true;
      }
    }
    window.onload =  function() {
      kindChanged();
    }
  </script>
@endsection

resources/views/transaction/delete.blade.php
@extends('layouts.app')

@section('styles')
  <style>
    .icon-file {
      height: 3rem;
      width: 3rem;
    }
  </style>
@endsection

@section('content')
  <div class="container">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Delete Transaction</h5>
      </div>
      <div class="card-body">
        <form method="post" action="{{ route('transaction.destroy', $transaction->id) }}" >
          @csrf
          @method('DELETE')

          <div class="row">

            <div class="col-md-4">
              @if ($transaction->pair)
                <div class="form-group">
                  <label for="account_from">Account From:</label>
                  <input
                    readonly  
                    id="account_from" 
                    class="form-control" 
                    type="text"
                    name="account_from" 
                    value="{{ $transaction_from->account->description }}"
                  >
                </div>
                <div class="form-group">
                  <label for="account_from">Account To:</label>
                  <input
                    readonly  
                    id="account_from" 
                    class="form-control" 
                    type="text"
                    name="account_from" 
                    value="{{ $transaction_to->account->description }}"
                  >
                </div>
              @else
                <div class="form-group">
                  <label for="account_from">Account From:</label>
                  <input
                    readonly  
                    id="account_from" 
                    class="form-control" 
                    type="text"
                    name="account_from" 
                    value="{{ $transaction->account->description }}"
                  >
                </div>
              @endif
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <label for="kind_id">Kind:</label>
                <input
                  readonly  
                  id="kind_id" 
                  class="form-control" 
                  type="text"
                  name="kind_id" 
                  value="{{ $transaction->kind->name }}"
                >
              </div>
              <div class="form-group">
                <label for="category_id">Category:</label>
                <input
                  readonly  
                  id="category_id" 
                  class="form-control" 
                  type="text"
                  name="category_id" 
                  value="{{ $transaction->category->description }}"
                >
              </div>
            </div>

            <div class="col-md-4">
              <div class="form-group">
                <label for="date">Date:</label>
                <input
                  readonly  
                  id="date" 
                  class="form-control" 
                  type="text"
                  name="date" 
                  value="{{ $transaction->date }}"
                >
              </div>
            </div>

          </div>

          <div class="row">

            <div class="col-md-6">
              <div class="form-group">
                <label for="amount">Amount:</label>
                <input
                  readonly  
                  id="amount" 
                  class="form-control" 
                  type="text" 
                  name="amount"
                  value="{{ $transaction->amount }}">
              </div>
            </div>

            <div class="col-md-6">
              <div class="form-group">
                <label for="detail">Detail:</label>
                <input
                  readonly  
                  id="detail" 
                  class="form-control" 
                  type="text" 
                  name="detail"
                  value="{{ $transaction->detail }}">
              </div>
            </div>

          </div>
          <button type="submit" class="btn btn-outline-danger">Delete</button>
          <a class="btn btn-outline-primary" href="{{ route('transaction.index') }}">Back</a>
        </form>
      </div>
    </div>
  </div>
@endsection

resources/views/transaction/index.blade.php
@extends('layouts.app')

@section('styles')
  <style>
    a {
      text-decoration: none;
    }
    tr {
      text-align: center;
    }
    .btn {
      margin: 1.5rem 0 1.5rem 0;
    }
    .icon-file {
      height: 2rem;
      width: 2rem;
    }
  </style>
@endsection

@section('content')
  <div class="container">
    <a class="btn btn-outline-light" href="{{ route('transaction.create') }}">Create</a>
    @if (session('message-success'))
      <p class="message message-success">{{ session('message-success') }}</p>
    @endif
    @if (session('message-info'))
      <p class="message message-info">{{ session('message-info') }}</p>
    @endif
    @error('error')
      <p class="message message-danger">{{ $message }}</p>
    @enderror
    <table class="table table-sm table-hover">
      <thead>
        <tr>
          <th>Account</th>
          <th>Category</th>
          <th>Amount</th>
          <th>Kind</th>
          <th>Detail</th>
          <th>Options</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($transactions as $transaction)
          <tr>
            <td>{{ $transaction->account->name }}</td>
            <td>{{ $transaction->category->description }}</td>
            <td>{{ $transaction->amount }}</td>
            <td>{{ $transaction->kind->name }}</td>
            <td>{{ $transaction->detail }}</td>
            <td>
              <a href="{{ route('transaction.edit', $transaction->id) }}">
                <i class="fas fa-edit fa-lg"></i>
              </a>
              -
              <a href="{{ route('transaction.show', $transaction->id) }}">
                <i class="fas fa-trash-alt fa-lg"></i>
              </a>
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>
    {{ $transactions->links() }}
  </div>
@endsection

resources/views/transaction/update.blade.php
@extends('layouts.app')

@section('styles')
  <style>
    .icon-file {
      height: 3rem;
      width: 3rem;
    }
  </style>
@endsection

@section('content')
  <div class="container">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Update Transaction</h5>
      </div>
      <div class="card-body">
        <form method="post" action="{{ route('transaction.update', $transaction->id) }}">
          @csrf
          @method('PUT')

          <div class="form-group">
            <label for="date">Date:</label>
            <input 
              id="date" 
              class="form-control" 
              type="date" 
              name="date" 
              max="{{ date('Y-m-d') }}" 
              value="{{ $transaction->date }}"
            >
          </div>
          @error('date')
            <p class="message message-danger">{{ $errors->first('date') }}</p>
          @enderror
          <div class="form-group">
            <label for="amount">Amount:</label>
            <input 
              id="amount" 
              class="form-control @error('amount') is-invalid @enderror" 
              type="number" 
              name="amount"
              step=".000001"
              min=".000001"
              value="{{ $transaction->amount }}">
          </div>
          @error('amount')
            <p class="message message-danger">{{ $errors->first('amount') }}</p>
          @enderror
          <div class="form-group">
            <label for="detail">Detail:</label>
            <input 
              id="detail" 
              class="form-control @error('detail') is-invalid @enderror" 
              type="text" 
              name="detail"
              value="{{ $transaction->detail }}">
          </div>
          @error('detail')
            <p class="message message-danger">{{ $errors->first('detail') }}</p>
          @enderror
          
          <button type="submit" class="btn btn-outline-success">Update</button>
          <a class="btn btn-outline-primary" href="{{ route('transaction.index') }}">Back</a>
        </form>
      </div>
    </div>
  </div>
  
@endsection

@section('javascript')
  <script type="text/javascript">
    window.onload =  function() {
      var select = document.getElementById("icon_name");
      document.getElementById('select_icon').className = select.options[select.selectedIndex].value + ' fa-4x';
      select.onchange = function() {
        document.getElementById('select_icon').className = select.options[select.selectedIndex].value + ' fa-4x';
      }
    }
  </script>
@endsection