routes/web.php
<?php
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Socialite 
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('user.local_currency/{id}', 'UserController@setLocalCurrency')->name('user.local_currency');
Route::post('user/store_exchange_rates/{id}', 'UserController@store_exchange_rates')->name('user.store_exchange_rates');
Route::get('user/exchange_rates/{id}', 'UserController@exchange_rates')->name('user.exchange_rates');


Route::resource('currency', 'CurrencyController');
Route::post('currency/add', 'CurrencyController@add')->name('currency.add');

Route::resource('account', 'AccountController');
Route::post('account/{id}/transactions', 'AccountController@transactions')->name('account.transactions');

Route::resource('transaction', 'TransactionController');
Route::resource('category', 'CategoryController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        'user_id', 'category_id', 'kind_id', 'icon_id', 'icon_file', 'description', 'monthly_budget'
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
    
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function kind()
    {
        return $this->belongsTo(Kind::class);
    }

    public function icon()
    {
        return $this->belongsTo(Icon::class);
    }

    public function categories()
    {
        return $this->hasMany(Category::class);
    }

    public function transactions()
    {
        return $this->hasMany(Transaction::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\File;
use Illuminate\Support\Facades\Storage;

use Auth;
use App\Kind;
use App\Category;
use App\Icon;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        return view('category.index', [
            'categories' => Auth::user()->categories()->paginate(10)
        ]);
    }

    public function create()
    {
        return view('category.create', [
            'categories' => Auth::user()->categories,
            'kinds' => Kind::all(),
            'icons' => Icon::all()->sortBy('label')
        ]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'category_id' => 'nullable|exists:categories,id',
            'kind_id' => 'required|exists:kinds,id',
            'icon_file' => 'nullable|image',
            'icon_name' => 'nullable|exists:icons,name',
            'description' => 'required|max:255|unique:categories,description,null,null,user_id,' . Auth::user()->id,
            'monthly_budget' => 'nullable|numeric|min:0.000001'
        ]);
        $category = Category::create([
            'user_id' => Auth::user()->id,
            'category_id' => $request['category_id'],
            'kind_id' => $request['kind_id'],
            'description' => $request['description'],
            'monthly_budget' => $request['monthly_budget']
        ]);
        if ($request['icon_file']) {
            $category->update([
                'icon_file' => Storage::putFileAs(
                    'icons/' . Auth::user()->id, 
                    $request['icon_file'],
                    'category_' . $category->id . '.' . $request['icon_file']->getClientOriginalExtension()
                )
            ]);
        } elseif($request['icon_name']) {
            $category->update([
                'icon_id' => Icon::where('name', $request['icon_name'])->first()->id
            ]);
        }
        return redirect(route('category.index'))->with([
            'message-success' => 'Category created correctly!'
        ]);
    }

    public function show(Category $category)
    {
        if ($category->description == 'Transfer') {
            return redirect()->back()->withErrors([
                'error' => 'You can\'t delete this category'
            ]);
        }
        return view('category.delete', [
            'category' => $category
        ]);
    }

    public function edit(Category $category)
    {
        return view('category.update', [
            'category' => $category,
            'categories' => Category::where('user_id', Auth::user()->id)->where('id', '!=', $category->id)->get(),
            'kinds' => Kind::all(),
            'icons' => Icon::all()->sortBy('label')
        ]);
    }

    public function update(Request $request, Category $category)
    {
        $request->validate([
            'icon_file' => 'nullable|image',
            'icon_name' => 'nullable|exists:icons,name',
            'monthly_budget' => 'nullable|numeric|min:0.000001'
        ]);
        if ($category->description == 'Transfer') {
            $category->update([
                'monthly_budget' => $request['monthly_budget']
            ]);
        } else {
            $request->validate([
                'category_id' => 'nullable|exists:categories,id,id,!' . $category->id,
                'kind_id' => 'required|exists:kinds,id',
                'description' => 'required|max:255|unique:categories,description,' . $category->id . ',id,user_id,' . Auth::user()->id
            ]);
            $category->update([
                'category_id' => $request['category_id'],
                'kind_id' => $request['kind_id'],
                'description' => $request['description'],
                'monthly_budget' => $request['monthly_budget']
            ]);
        }
        if (!$request['keep_icon_file']) {
            if ($category->icon_file) {
                $category->update([
                    'icon_file' => null
                ]);
            }
            if ($request['icon_file']) {
                $category->update([
                    'icon_file' => Storage::putFileAs(
                            'icons/' . Auth::user()->id, 
                            $request['icon_file'],
                            'category_' . $category->id . '.' . $request['icon_file']->getClientOriginalExtension()
                        ),
                    'icon_id' => null
                ]);
            } elseif($request['icon_name']) {
                $category->update([
                    'icon_id' => Icon::where('name', $request['icon_name'])->first()->id,
                    'icon_file' => null
                ]);
            } else {
                $category->update([
                    'icon_id' => null,
                    'icon_file' => null
                ]);
            }
        } 
        return redirect(route('category.index'))->with([
            'message-success' => 'Account updated correctly!'
        ]);
    }

    public function destroy(Category $category)
    {
        if ($category->categories()->exists()) {
            return redirect()->back()->withErrors([
                'error' => 'This category has categories related to it, you can\'t delete it'
            ]);
        }
        if ($category->transactions()->exists()) {
            return redirect()->back()->withErrors([
                'error' => 'This category has transactions related to it, you can\'t delete it'
            ]);
        }
        $account->delete();
        return redirect(route('account.index'))->with([
            'message-success' => 'Account deleted correctly!'
        ]);
    }
}

resources/views/category/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Create an Category</h5>
      </div>
      <div class="card-body">
        <form method="post" action="{{ route('category.store') }}" enctype="multipart/form-data">
          @csrf

          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <label for="category_id">Category Father:</label>
                <select 
                class="form-control @error('category_id') is-invalid @enderror" 
                name="category_id" 
                id="category">
                  <option value="">Without Father</option>
                  @foreach ($categories as $category)
                    @if (old('category_id') == $category->id)
                      <option value="{{ $category->id }}" selected>
                        {{ $category->description }}
                      </option>
                    @else
                      <option value="{{ $category->id }}">
                        {{ $category->description }}
                      </option>
                    @endif
                  @endforeach
                </select>
              </div>
              @error('category_id')
                <p class="message message-danger">{{ $errors->first('category_id') }}</p>
              @enderror
              <div class="form-group">
                <label for="kind_id">Kind:</label>
                <select 
                class="form-control @error('kind_id') is-invalid @enderror" 
                name="kind_id" 
                id="kind">
                  @foreach ($kinds as $kind)
                    @if (old('kind_id') == $kind->id)
                      <option value="{{ $kind->id }}" selected>
                        {{ $kind->name }}
                      </option>
                    @else
                      <option value="{{ $kind->id }}">
                        {{ $kind->name }}
                      </option>
                    @endif
                  @endforeach
                </select>
              </div>
              @error('kind_id')
                <p class="message message-danger">{{ $errors->first('kind_id') }}</p>
              @enderror
              <div class="form-group">
                <label for="description">Description:</label>
                <input 
                class="form-control @error('description') is-invalid @enderror" 
                type="text" 
                name="description" 
                id="description" 
                value="{{ old('description') }}">
              </div>
              @error('description')
                <p class="message message-danger">{{ $errors->first('description') }}</p>
              @enderror
            </div>
            <div class="col-md-6">
              <div class="row">
                <div class="col-md-9">
                  <div class="form-group">
                    <label for="icon_name">We have {{ count($icons) }} icons for you. You can choose one if you wish:</label>
                    <select 
                    class="form-control @error('icon_name') is-invalid @enderror" 
                    name="icon_name" 
                    id="icon_name">
                      <option value="">Without icon</option>
                      @foreach ($icons as $icon)
                        @if (old('icon_name') == $icon->name)
                          <option value="{{ $icon->name }}" selected>
                            {{ $icon->label }}
                          </option>
                        @else
                          <option value="{{ $icon->name }}">
                            {{ $icon->label }}
                          </option>
                        @endif
                      @endforeach
                    </select>
                  </div>
                  @error('icon_name')
                    <p class="message message-danger">{{ $errors->first('icon_name') }}</p>
                  @enderror
                </div>
                <div class="col-md-3">
                  <i class="" id="select_icon"></i>
                </div>
              </div>
              <div class="form-group">
                <label for="icon_file">Or you can use your own icon if you wish:</label>
                <input type="file" class="form-control-file" id="icon_file" name="icon_file" accept="image/*">
              </div>
              <p class="message message-info">If you select one of our icons but you upload your own, yours will be set.</p>
              @error('icon_file')
                <p class="message message-danger">{{ $errors->first('icon_file') }}</p>
              @enderror
              <div class="form-group">
                <label for="monthly_budget">Monthly Budget:</label>
                <input 
                class="form-control @error('monthly_budget') is-invalid @enderror" 
                type="number" 
                name="monthly_budget" 
                id="monthly_budget" 
                value="{{ old('monthly_budget') }}"
                step=".000001">
              </div>
              @error('monthly_budget')
                <p class="message message-danger">{{ $errors->first('monthly_budget') }}</p>
              @enderror
            </div>
          </div>
          <button type="submit" class="btn btn-outline-success">Create</button>
          <a class="btn btn-outline-primary" href="{{ route('category.index') }}">Back</a>
        </form>
      </div>
    </div>
  </div>
  
@endsection

@section('javascript')
  <script type="text/javascript">
    window.onload =  function() {
      var select = document.getElementById("icon_name");
      document.getElementById('select_icon').className = select.options[select.selectedIndex].value + ' fa-4x';
      select.onchange = function() {
        document.getElementById('select_icon').className = select.options[select.selectedIndex].value + ' fa-4x';
      }
    }
  </script>
@endsection

resources/views/category/delete.blade.php
@extends('layouts.app')

@section('styles')
  <style>
    .icon-file {
      height: 3rem;
      width: 3rem;
    }
  </style>
@endsection

@section('content')
  <div class="container">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Delete Category</h5>
      </div>
      <div class="card-body">
        @error('error')
          <p class="message message-danger">{{ $message }}</p>
        @enderror
        <form method="post" action="{{ route('category.destroy', $category->id) }}" >
          @csrf
          @method('DELETE')

          <div class="row">
            @if ($category->category)
              <div class="col-md-6">
                <div class="form-group">
                  <label for="category_id">Father:</label>
                  <input id="category_id" class="form-control" type="text" name="category_id" value="{{ $category->category->description }}" readonly>
                </div>
              </div>
            @endif
            @if ($category->kind)
              <div class="col-md-6">
                <div class="form-group">
                  <label for="kind_id">Kind:</label>
                  <input id="kind_id" class="form-control" type="text" name="kind_id" value="{{ $category->kind->name }}" readonly>
                </div>
              </div>
            @endif
            <div class="col-md-6">
              <div class="form-group">
                <label for="description">Description:</label>
                <input id="description" class="form-control" type="text" name="description" value="{{ $category->description }}" readonly>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <label for="monthly_budget">Monthly Budget:</label>
                <input id="monthly_budget" class="form-control" type="text" name="monthly_budget" value="{{ $category->user->localCurrency->symbol }} " readonly>
              </div>
            </div>
          </div>
          <div class="form-group">
            <label for="icon_name">Icon:</label>
            @if ($category->icon)
              <br>
              <i class="{{ $category->icon->name }} fa-4x"></i>
            @elseif ($category->icon_file)
              <br>
              <img src="{{ asset('storage/' . $category->icon_file) }}" alt="Icon" class="icon-file">
            @else 
              <p class="message message-info">This category doesn't have an icon</p>
            @endif
          </div>
          <button type="submit" class="btn btn-outline-danger">Delete</button>
          <a class="btn btn-outline-primary" href="{{ route('category.index') }}">Back</a>
        </form>
      </div>
    </div>
  </div>
@endsection

@section('javascript')
  <script type="text/javascript">
    window.onload =  function() {
      var value = <?php echo $category->monthly_budget; ?>;
      document.getElementById('monthly_budget').value += value.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1,");
    }
  </script>
@endsection

resources/views/category/index.blade.php
@extends('layouts.app')

@section('styles')
  <style>
    a {
      text-decoration: none;
    }
    tr {
      text-align: center;
    }
    .btn {
      margin: 1.5rem 0 1.5rem 0;
    }
    .icon-file {
      height: 2rem;
      width: 2rem;
    }
  </style>
@endsection

@section('content')
  <div class="container">
    <a class="btn btn-outline-light" href="{{ route('category.create') }}">Create</a>
    @if (session('message-success'))
      <p class="message message-success">{{ session('message-success') }}</p>
    @endif
    @if (session('message-info'))
      <p class="message message-info">{{ session('message-info') }}</p>
    @endif
    @error('error')
      <p class="message message-danger">{{ $message }}</p>
    @enderror
    <table class="table table-sm table-hover">
      <thead>
        <tr>
          <th>Father</th>
          <th>Kind</th>
          <th>Description</th>
          <th>Icon</th>
          <th>Monthly Budget</th>
          <th>Options</th>
        </tr>
      </thead>
      <tbody>
        @foreach ($categories as $category)
          <tr>
            <td>
              @if ($category->category)
                {{ $category->category->description }}
              @endif
            </td> 
            <td>{{ $category->kind->name }}</td>
            <td>{{ $category->description }}</td>
            <td>
              @if ($category->icon)
                <i class="{{ $category->icon->name }} fa-2x"></i>
              @endif
              @if ($category->icon_file)
                <img src="{{ asset('storage/' . $category->icon_file) }}" alt="Icon" class="icon-file">
              @endif
            </td>
            <td>
              @if ($category->monthly_budget)
                {{ $category->user->localCurrency->symbol }}<span class="monthly_budget">{{ $category->monthly_budget }}</span>
              @endif
            </td> 
            <td>
              <a href="{{ route('category.edit', $category->id) }}">
                <i class="fas fa-edit fa-lg"></i>
              </a>
              -
              <a href="{{ route('category.show', $category->id) }}">
                <i class="fas fa-trash-alt fa-lg"></i>
              </a>
            </td>
          </tr>
        @endforeach
      </tbody>
    </table>
    {{ $categories->links() }}
  </div>
@endsection
 
@section('javascript')
  <script type="text/javascript">
    window.onload =  function() {
      var select = document.getElementById("icon_name");
      var monthly_budgets = document.getElementsByClassName('monthly_budget');
      for (let i = 0; i < monthly_budgets.length; i++) {
        var value = monthly_budgets[i].innerHTML;
        monthly_budgets[i].innerHTML = ' ' + value.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1,");
      }
    }
  </script>
@endsection

resources/views/category/update.blade.php
@extends('layouts.app')

@section('styles')
  <style>
    .icon-file {
      height: 3rem;
      width: 3rem;
    }
  </style>
@endsection

@section('content')
  <div class="container">
    <div class="card">
      <div class="card-header">
        <h5 class="card-title">Update Category</h5>
      </div>
      <div class="card-body">
        @error('error')
          <p class="message message-danger">{{ $message }}</p>
        @enderror
        <form method="post" action="{{ route('category.update', $category->id) }}" enctype="multipart/form-data">
          @csrf
          @method('PUT')

          <div class="row">
            @if ($category->description != 'Transfer')
              <div class="col-md-6">
                <div class="form-group">
                  <label for="category_id">Category Father:</label>
                  <select 
                  class="form-control @error('category_id') is-invalid @enderror" 
                  name="category_id" 
                  id="category">
                    <option value="">Without Father</option>
                    @foreach ($categories as $cat)
                      @if ($category->category)
                        @if ($category->category->id == $cat->id)
                          <option value="{{ $cat->id }}" selected>
                            {{ $cat->description }}
                          </option>
                        @else
                          <option value="{{ $cat->id }}">
                            {{ $cat->description }}
                          </option>
                        @endif
                      @else
                        <option value="{{ $cat->id }}">
                          {{ $cat->description }}
                        </option>
                      @endif
                    @endforeach
                  </select>
                </div>
                @error('category_id')
                  <p class="message message-danger">{{ $errors->first('category_id') }}</p>
                @enderror
                <div class="form-group">
                  <label for="kind_id">Kind:</label>
                  <select 
                  class="form-control @error('kind_id') is-invalid @enderror" 
                  name="kind_id" 
                  id="kind">
                    @foreach ($kinds as $kind)
                      @if ($category->kind->id == $kind->id)
                        <option value="{{ $kind->id }}" selected>
                          {{ $kind->name }}
                        </option>
                      @else
                        <option value="{{ $kind->id }}">
                          {{ $kind->name }}
                        </option>
                      @endif
                    @endforeach
                  </select>
                </div>
                @error('kind_id')
                  <p class="message message-danger">{{ $errors->first('kind_id') }}</p>
                @enderror
                <div class="form-group">
                  <label for="description">Description:</label>
                  <input 
                  class="form-control @error('description') is-invalid @enderror" 
                  type="text" 
                  name="description" 
                  id="description" 
                  value="{{ $category->description }}">
                </div>
                @error('description')
                  <p class="message message-danger">{{ $errors->first('description') }}</p>
                @enderror
              </div>
            @endif
            
            <div class="col-md-6">
              <div class="row">
                <div class="col-md-9">
                  <div class="form-group">
                    <label for="icon_name">We have {{ count($icons) }} icons for you. You can choose one if you wish:</label>
                    <select 
                    class="form-control @error('icon_name') is-invalid @enderror" 
                    name="icon_name" 
                    id="icon_name">
                      <option value="">Without icon</option>
                      @foreach ($icons as $icon)
                        @if ($category->icon)
                          @if ($category->icon->name == $icon->name)
                            <option value="{{ $icon->name }}" selected>
                              {{ $icon->label }}
                            </option>
                          @else
                            <option value="{{ $icon->name }}">
                              {{ $icon->label }}
                            </option>
                          @endif
                        @else
                          <option value="{{ $icon->name }}">
                            {{ $icon->label }}
                          </option>
                        @endif
                      @endforeach
                    </select>
                  </div>
                  @error('icon_name')
                    <p class="message message-danger">{{ $errors->first('icon_name') }}</p>
                  @enderror
                </div>
                <div class="col-md-3">
                  <i class="" id="select_icon"></i>
                </div>
              </div>
              <div class="row">
                <div class="col-md-10">
                  <div class="form-group">
                    <label for="icon_file">Or you can use your own icon if you wish:</label>
                    <input type="file" class="form-control-file" id="icon_file" name="icon_file" accept="image/*">
                  </div>
                  <p class="message message-info">If you select one of our icons but you upload your own, yours will be set.</p>
                  @error('icon_file')
                    <p class="message message-danger">{{ $errors->first('icon_file') }}</p>
                  @enderror
                </div>
                <div class="col-md-2">
                  @if ($category->icon_file)
                    <img src="{{ asset('storage/' . $category->icon_file) }}" alt="Icon" class="icon-file">
                  @endif
                </div>
              </div>
              @if ($category->icon_file)
                <div class="row">
                  <div class="col-md-6 offset-md-6">
                    <div class="form-check">
                      <input id="keep_icon_file" class="form-check-input" type="checkbox" name="keep_icon_file" value="true">
                      <label for="keep_icon_file" class="form-check-label">I want to keep my old icon</label>
                    </div>
                    <p class="message message-info">If you already had set your own icon and don't check this option or don't upload a new icon, your old icon will be deleted.</p>
                  </div>
                </div>
              @endif
              <div class="form-group">
                <label for="monthly_budget">Monthly Budget:</label>
                <input 
                class="form-control @error('monthly_budget') is-invalid @enderror" 
                type="number" 
                name="monthly_budget" 
                id="monthly_budget" 
                value="{{ $category->monthly_budget }}"
                step=".000001">
              </div>
              @error('monthly_budget')
                <p class="message message-danger">{{ $errors->first('monthly_budget') }}</p>
              @enderror
            </div>
          </div>
          @if ($category->icon_file)
            <div class="row">
              <div class="col-md-6 offset-md-6">
                <div class="form-check">
                  <input id="keep_icon_file" class="form-check-input" type="checkbox" name="keep_icon_file" value="true">
                  <label for="keep_icon_file" class="form-check-label">I want to keep my old icon</label>
                </div>
                <p class="message message-info">If you already had set your own icon and don't check this option or don't upload a new icon, your old icon will be deleted.</p>
              </div>
            </div>
            @endif
          
          <button type="submit" class="btn btn-outline-success">Update</button>
          <a class="btn btn-outline-primary" href="{{ route('category.index') }}">Back</a>
        </form>
      </div>
    </div>
  </div>
  
@endsection

@section('javascript')
  <script type="text/javascript">
    window.onload =  function() {
      var select = document.getElementById("icon_name");
      document.getElementById('select_icon').className = select.options[select.selectedIndex].value + ' fa-4x';
      select.onchange = function() {
        document.getElementById('select_icon').className = select.options[select.selectedIndex].value + ' fa-4x';
      }
    }
  </script>
@endsection