routes/web.php
<?php
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//Socialite 
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('user.local_currency/{id}', 'UserController@setLocalCurrency')->name('user.local_currency');
Route::post('user/store_exchange_rates/{id}', 'UserController@store_exchange_rates')->name('user.store_exchange_rates');
Route::get('user/exchange_rates/{id}', 'UserController@exchange_rates')->name('user.exchange_rates');


Route::resource('currency', 'CurrencyController');
Route::post('currency/add', 'CurrencyController@add')->name('currency.add');

Route::resource('account', 'AccountController');
Route::post('account/{id}/transactions', 'AccountController@transactions')->name('account.transactions');

Route::resource('transaction', 'TransactionController');
Route::resource('category', 'CategoryController');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    @include('layouts.scripts')
    @yield('scripts')

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Pangolin&display=swap" rel="stylesheet">

    
    <!-- Styles -->
    @include('layouts.styles')
    @yield('styles')
    
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light shadow-sm" id="navbar">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>
    
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
    
                    </ul>
    
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        <i class="fas fa-sign-out-alt fa-lg"></i> - {{ __('Logout') }}
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                    <a class="dropdown-item" href="{{ route('currency.index') }}">
                                        <i class="fas fa-coins fa-lg"></i> - Currencies
                                    </a>
                                    <a class="dropdown-item" href="{{ route('account.index') }}">
                                        <i class="fas fa-piggy-bank fa-lg"></i> - Accounts
                                    </a>
                                    <a class="dropdown-item" href="{{ route('transaction.index') }}">
                                        <i class="fas fa-arrows-alt fa-lg"></i> - Transactions
                                    </a>
                                    <a class="dropdown-item" href="{{ route('category.index') }}">
                                        <i class="fas fa-boxes fa-lg"></i> - Categories
                                    </a>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
    
        <main>
            @yield('content')
        </main>
    </div>

    @yield('javascript')

</body>
</html>

resources/views/layouts/scripts.blade.php
<script src="{{ asset('js/app.js') }}" defer></script>

resources/views/layouts/styles.blade.php
<link href="{{ asset('css/app.css') }}" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">

<style>
  .message {
    display: block;
  }
  .message-danger {
    color: #dc3545!important;
  }
  .message-success {
    color: #14a76c!important;
  }
  .message-info {
    color: #ff652f!important;
  }
</style>

<style>
  body {
    background-color: #0b0c10;
    font-family: 'Pangolin', cursive;
  }
  #navbar {
    background-color: #1f2833;
    min-height: 10vh;
  }
  .navbar-light .navbar-brand,
  .navbar-light .navbar-nav .nav-link,
  .card-header {
    color: white !important;
  }
  .dropdown-item {
    background-color: #1f2833;
    color: white;
    border-color: #1f2833;
  }
  .dropdown-item:hover {
    background-color: #0b0c10;
    color: white;
    border-color: #1f2833;
  }
  .dropdown-menu {
    border-color: #1f2833;
    background-color: #0b0c10;
  }
  .card,
  .card-header {
    border-color: #1f2833;
  }
  .card-header,
  .card-footer {
    background-color: #1f2833;
  }
  .card-body {
    background-color: #0b0c10;
    color:  white;
  }
  .form-control,
  .form-control:read-only {
    background-color: #0b0c10;
    color:  #c5c6c7;
  }
  .form-control:focus,
  option {
    background-color: #0b0c10;
    color:  white;
  }
  input:read-only {
    pointer-events: none;
  }
  .table {
    color: white;
  }
  .table-hover>tbody>tr:hover,
  .table-hover>tbody>tr:hover>td>a>.fas,
  .table-hover>tbody>tr:hover>td>a>.far,
  .table-hover>tbody>tr:hover>td>a>.fab {
    background-color: #1f2833;
    color: white;
  }
  td>a>.fas, 
  td>a>.far, 
  td>a>.fab {
    color: white;
  }
  .btn {
    color: white !important; 
  }
  .btn:hover {
    color: #1f2833 !important; 
  }
  th {
    font-size: 1.25rem;
  }
  main{
    min-height: 90vh;
    min-width: 100vw;
  }
  .row {
    display: flex;
    align-items: center;
    justify-content: center;
  }
  .card {
    margin-top: 1.5rem;
  }
</style>